#!/bin/bash

sudo apt-get update -y

sudo apt install apache2

sudo systemctl start apache2

sudo systemctl status apache2

sudo usermod -aG www-data $USER

sudo chown ubuntu /var/www/html

touch /var/www/html/index.html

sudo chmod 666 /var/www/html/index.html

echo "<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <title>My Web Page</title>
	    </head>
	    <body>
	        <h1>Welcome to My Apache2 Server</h1>
		    <p>This is a simple webpage served using Apache2.</p>
		    </body>
		    </html>" > /var/www/html/index.html

echo "apache2 webserver install and run successfully"
